### ISSUE TITLE
Import of OPML fails to subscribe

### ISSUE THREAD

**Issue by TanukiKabuki** [stonega/tsacdop#11]
Not sure what's going on here, I am attempting to import from Podcast Addict OPML file and it says import success but subscription fails and nothing is added.

**Comment by stonega** [comment]
Hi. sorry for the issue, I have tested import the ompl file from Podcast Addict, and worked fine.
It would be helpful and grateful if you can send me your OMPl file to me at tsacdop.app@gmail.com 
Thanks!

**Comment by TanukiKabuki** [comment]
File sent to you. Should be in your inbox.
