### ISSUE TITLE
Publish to F-Droid?

### ISSUE THREAD

**Issue by Pentaphon** [stonega/tsacdop#13]
What the title says.

**Comment by benflap** [comment]
Now that you added podcast index, are you going to publish to F-Droid?

**Comment by stonega** [comment]
Good reminder! Thanks!  I will work on it in recent days.

**Comment by stonega** [comment]
> Now that you added podcast index, are you going to publish to F-Droid?

Tsacdop has been available on F-Droid. Cheers
