### ISSUE TITLE
cmpile failed.

### ISSUE THREAD

**Issue by huangyt** [stonega/tsacdop#15]
windows + Flutter 1.20.3 + JDK 1.8.0_261 + Dart 2.9.2

"flutter build apk", then

\AppData\Local\Pub\Cache\git\audio_service-4708034af4c94ca3390185d55083cd297f6db819\android\src\main\java\com\ryanheise\audioservice\AudioServicePlugin.javaʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣                            
1 ������                                                                
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
**Execution failed for task ':audio_service:compileReleaseJavaWithJavac'**. 
> Compilation failed; see the compiler error output for details.

**Comment by stonega** [comment]
I am testing a modified audio_service plugin, looks there is a issue with it, you might need to switch audio_seevice to official release in pubsepc file.
`audio_service: ^0.14.1`

**Comment by huangyt** [comment]
> I am testing a modified audio_service plugin, looks there is a issue with it, you might need to switch audio_seevice to official release in pubsepc file.
> `audio_service: ^0.14.1`

it's worked ! thank you!. i'm a new one for flutter, great job! but when i compiled a release version, it 's  got another wrong: **:app:validateSigningRelease**， thank you!

**Comment by stonega** [comment]
https://flutter.dev/docs/deployment/android
I think you need to create a keystore for release version.

**Comment by huangyt** [comment]
OK，thank you! tsacdop is a great app, and also thank you for your timely answer!
