### ISSUE TITLE
edit group name : can not move the cursor.

### ISSUE THREAD

**Issue by huangyt** [stonega/tsacdop#16]
group -> "+" , then create a group, like "aaa" -> "confirm" -> "**Edit group name**".
the cursor can't move.

**Comment by stonega** [comment]
Under current setting, you can only input a new group name instead edit the old name directly.
I think it is a good idea to make the name editable directly, I will change it.

**Comment by stonega** [comment]
Already changed. Thanks!
[commit](https://github.com/stonega/tsacdop/commit/7d873062ecbaeaf70119f2e28b6f493306c45986)
