### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by a936919** [stonega/tsacdop#17]
Import the file in the upper right corner of the software It should be an OPML file. Now it is a 
ompl file. It is also an error in Chinese translation
![S00911-22314750](https://user-images.githubusercontent.com/41937411/92938001-9d47b380-f47e-11ea-8ced-8e62e8ac1452.png)

**Comment by stonega** [comment]
Oh, thanks for the report!

**Comment by stonega** [comment]
Already fixed the typo, I will close this issue, thanks again!
