### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by a936919** [stonega/tsacdop#18]
It has been tried several times. In the podcast single episode search, if the current input method is not retrieved, it is unable to click the confirm button, resulting in no search
![Video_20200911_103906_75](https://user-images.githubusercontent.com/41937411/92938957-c3ba1e80-f47f-11ea-9c5b-ce4498de0e2a.gif)

**Comment by stonega** [comment]
I will have a check about this, thanks for the feedback! I will reply here when it is fixed.

**Comment by a936919** [comment]
@stonega Every time I enter the shownote interface, it will display a blank, and then it will display normally after two or three seconds. This is also the case when I have tried to use mobile cellular traffic. It should not be a network problem

**Comment by stonega** [comment]
@a936919 Yeah, it is not a network related issue, as the show notes is stored locally, it needs to be loaded and formatted (format url and email link) before displayed. I will try to improve the speed, thanks!
