### ISSUE TITLE
Feature Request: Desktop Support

### ISSUE THREAD

**Issue by gargakshit** [stonega/tsacdop#19]
You can have a uniform desktop support using [go-flutter](https://github.com/go-flutter-desktop/go-flutter)

**Comment by stonega** [comment]
Thanks for letting me know about this, I will definitely have a try to see how it works!

**Comment by stonega** [comment]
I have created a new project to build  a desktop version of Tsacdop, supports Windows first ,then Linux. 
I found that the desktop app have a totally different layout from widget perspective. I will keep both projects have the same database. And I try to use riverpod to manage state in desktop version.
https://github.com/stonega/tsacdop_desktop
