### ISSUE TITLE
Pub get failed

### ISSUE THREAD

**Issue by jr00n** [stonega/tsacdop#2]
Because xml >=3.7.0 depends on petitparser ^3.0.0 and every version of flutter_test from sdk depends on petitparser 2.4.0, xml >=3.7.0 is incompatible with flutter_test from sdk.
So, because tsacdop depends on both flutter_test any from sdk and xml 4.2.0, version solving failed.

❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale nl-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by stonega** [comment]
Sorry for the late reply, you need to update flutter package, as I want to use the latest version xml plugin. 
```
flutter update-packages --force-upgrade
````
