### ISSUE TITLE
Feature Request: Allow easier access to All podcasts.

### ISSUE THREAD

**Issue by C0deSeeker** [stonega/tsacdop#20]
Currently, access to all podcasts (where all subscribed podcasts are arranged alphabetically) is only possible through the 3-dot menu in the Group page. This makes it unnecessarily a three step process only to access the All Podcasts page. I have a possible solution that can solve this issue.
![Screenshot_20200916-143224170](https://user-images.githubusercontent.com/36724358/93335653-6b4e9c80-f844-11ea-90d0-897e9ed932b0.jpg)
What I'm proposing is to allow users to access group page by taping on the 'Home' and access All podcasts page by taping on See All. This way, users will be able to access both groups and all podcasts screen directly from the homepage.

**Comment by stonega** [comment]
Thanks for your suggestion, I would say this is a really good idea, it will be implemented in future release.

**Comment by stonega** [comment]
I have another solution, long press See All to open all podcast page, and tap Home to change group. 
This might be a better solution.

**Comment by C0deSeeker** [comment]
> 
> 
> I have another solution, long press See All to open all podcast page, and tap Home to change group.
> This might be a better solution.

Absolutely! This does seem a better option. Also, thanks for considering my suggestion.
