### ISSUE TITLE
[Feature] More options for playlist management

### ISSUE THREAD

**Issue by dutrieuc** [stonega/tsacdop#24]
Playlist sometimes get crowded, it could be nice to have the options to clear the playlist easily and to have a 'play after' button to insert an episode after the one being played.

I can get started on it if you like the idea

**Comment by dutrieuc** [comment]
I can get started on it if you like the idea

**Comment by stonega** [comment]
Both are good also needed features I think. 
Clear play button can be added in playlist page, and play after button in episode detail page and also add a popup item for it.
Looking forward to your work!

**Comment by dutrieuc** [comment]
I'm wondering if the two different playlist screens are going to stay that way. Is the plan to have them both in the app or are they going to merge in some ways ?

**Comment by stonega** [comment]
@dutrieuc I have no intention to change it, and  keep the playlist in player widget as simple as possible, if user want more options, go to the playlist page.  Sorry for the delay.

**Comment by stonega** [comment]
@dutrieuc I can confirm that both features have been supported in version 0.5.2, I will close this issue.
