### ISSUE TITLE
Keep podcast listen progress for more than most recently played

### ISSUE THREAD

**Issue by BradNut** [stonega/tsacdop#27]
As the title says I tend to listen to multiple podcasts during a day and sometimes switch between them before completing the full episode. I have not found a way to continue where I left off for any except the most recently played podcast. 

Since some of the podcasts as 2-3 hours long it becomes very tiresome finding my last position in multiple episodes. Is there a setting that I am missing or is this an intentional feature?

I would like to move to this podcast app over AntennaPod but at the moment this is what keeps me from moving.

**Comment by stonega** [comment]
![Screenshot_20201012-124224.png](https://user-images.githubusercontent.com/2262007/95706134-9a5ffe80-0c88-11eb-9bcd-0d13a418b5bc.png)

If I understand correctly, you can tap the timestamp to play from last position in history page. You can also find the time stamp in episode detail page.

**Comment by BradNut** [comment]
Hello. I am unsure where this screen is located. My settings history page looks like the following: 
![Settings History Page](https://user-images.githubusercontent.com/6621295/95764731-b69e7400-0c65-11eb-8f62-941b99ea5810.png)

Also, clicking on the time in this page does nothing.

I would assume pressing play on any episode I already have progress in would automatically resume my listening from the last time I listened but instead the episode starts over.

Also, I am able to see how far I was in the podcast when i go to the single episode view but clicking on that time signature starts playing the episode from the beginning.

![Single Episode View with History Timestamp](https://user-images.githubusercontent.com/6621295/95765156-4c3a0380-0c66-11eb-93ba-f02b50e29b38.png)

![After clicking the timestaml](https://user-images.githubusercontent.com/6621295/95765164-51974e00-0c66-11eb-8368-7b31a8469756.png)

**Comment by stonega** [comment]
![Screenshot_20201013-130658.png](https://user-images.githubusercontent.com/2262007/95817839-10ca3280-0d55-11eb-9bd7-f33fb2740ef0.png)

**Comment by BradNut** [comment]
I did not know that version of the history page existed but also using that page and tapping on the timestamp starts the podcast from the beginning for me.

Using Android 11 build of Tsacdop version 0.4.19.1036 from IzzyOnDroid.

![Screenshot_20201012-233212](https://user-images.githubusercontent.com/6621295/95824155-a75e0b80-0ce3-11eb-921d-4033485ee84e.png)
![Screenshot_20201012-233225](https://user-images.githubusercontent.com/6621295/95824166-aa58fc00-0ce3-11eb-8ccc-2ce9565fbe92.png)

Let me know if you need more info since I may be clearly missing something or have a setting or something incorrectly set.

**Comment by stonega** [comment]
Thanks for the reply, I will try to find what happened, there is also another solution.![Screenshot_20201014-124559.png](https://user-images.githubusercontent.com/2262007/95944783-9adcce80-0e1b-11eb-90d7-e914e086cde4.png)

**Comment by stonega** [comment]
I have fixed the issue in v0.5.0. Please let me know if it works for you after update.

**Comment by BradNut** [comment]
Update v0.5.0 seems to have fixed that issue. Thank you!

**Comment by meonkeys** [comment]
What would you think about making "resume where I left off" the default action when streaming or playing any downloaded podcast? (I'd like this)
