### ISSUE TITLE
Cant subscribe to any ThaiPBS podcasts found with the embeded search engine 

### ISSUE THREAD

**Issue by ppp987** [stonega/tsacdop#3]

**Comment by stonega** [comment]
Sorry for that, I found that the RSS link returned from search engine is unavailable. I will report this issue to the search engine provider, hope they will fix it soon. 
Thanks!

**Comment by stonega** [comment]
@ppp987  Looks like you need to search "Thai PBS" instead of "ThaiPBS" to get newest podcasts which should be subscribed with no issue.  If you search "ThaiPBS",  most of the results are outdated podcasts.  Could you have a try and let me know if it worked?

**Comment by ppp987** [comment]
It works this way, thank you very much.
