### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by a936919** [stonega/tsacdop#34]
The podcast avatar of 0.5.5 downloaded from the play store cannot be displayed or the wrong avatar is displayed

![Screenshot_2021-01-28-00-34-06-315_com stonegate tsacdop](https://user-images.githubusercontent.com/41937411/106022963-fad64880-608b-11eb-9b04-a767f5004a6c.jpg)

**Comment by stonega** [comment]
SORRY for the issue, I will fix it tonight and release the update.

**Comment by stonega** [comment]
It has been fixed in v0.5.6.
You can refresh artwork in podcast setting to get back the right image, or you can resubscribe the podcast. 
Sorry for the issue.
