### ISSUE TITLE
Large artwork and chapters

### ISSUE THREAD

**Issue by benflap** [stonega/tsacdop#35]
What are your plans/thoughts on making the podcast artwork larger so that you can add support for chapter artwork? Either the [podcast index chapter spec](https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#chapters) or the spec that is used by podcasts like [ATP](https://atp.fm/).

**Comment by stonega** [comment]
Yeah, I have been thinking about it . I have added new funding namespace support, and I am working on support more , this is more about a design work, I need to think more how to  how to intergate it.   
Thanks for youe support  :)

**Comment by stonega** [comment]
This feature has been supported in v0.5.8, have a try :)

**Comment by benflap** [comment]
When is it that you parse the json file. Is it when the app sees there's a new episode or when the episode is downloaded?

Most of the podcasts I listen to that support the `<podcast:chapters>` tag, add chapters after the episode is published. I think it would be cool if every time I pressed play the app would fetch the chapters json file and update the chapters for that episode.

**Comment by stonega** [comment]
The json file is downloaded and cached locally when you play the episode
and want to check the chapters. Only the link is saved in database.

ben <notifications@github.com> 於 2021年2月13日 週六 23:03 寫道：
