### ISSUE TITLE
bug: Timcast IRL not downloading

### ISSUE THREAD

**Issue by benflap** [stonega/tsacdop#37]
Timcast IRL is not downloading. Specifically episodes 215 and 216 did not download. However, episode 214 did download.

Here's the link to the RSS feed: <https://feeds.buzzsprout.com/238686.rss>

**Comment by stonega** [comment]
I'll have a check about it 🙂

**Comment by stonega** [comment]
It was caused by the '/' in the episode titile, my fault, I have fixed it, will update soon.

**Comment by benflap** [comment]
I figured it was a weird edge case thing like that. Thanks for the quick response🤙
