### ISSUE TITLE
Suggestion: Publish Android App to SkyDroid

### ISSUE THREAD

**Issue by redsolver** [stonega/tsacdop#38]
[SkyDroid](https://skydroid.app/) is a decentralized domain-based App Store for Android which puts the developer in full control of updates.

An app is published on a domain name by adding a TXT record, for example `app.example.com`, and the user can then install the app by entering `app.example.com` in the SkyDroid app or by simply clicking a link (like in a web browser). So it's basically a direct APK download with the added convenience of auto-updates, rich metadata and better security.

Publishing on SkyDroid is really fast and you only need a domain name and the [SkyDroid CLI](https://github.com/redsolver/skydroid-cli). Then just follow the instructions in the CLI Repo.

**Comment by stonega** [comment]
Looks like a really intersting project, you have done great job,  I am curious where are those apk saved?

**Comment by redsolver** [comment]
Thanks, the CLI tool uploads APKs to the decentralized Skynet CDN by default. (Short explanation: When a file is uploaded to a Skynet portal like https://siasky.net/, you get a skylink which can then be used to download the file on any other Skynet portal, for example https://skyportal.xyz/. This gives every developer and user the freedom to choose any portal while still keeping access to all of their data). Alternatively it's also possible to just upload the APK file to GitHub releases or another website with direct downloads, but that's of course "less decentralized".

**Comment by stonega** [comment]
Thanks for the reply, I am learning about blockchains and first time know about the skynet. Looks promising, can it be used to backup user data?
I have already added yml fileds in the repo, but I use github actions to build, I need some time to get it done.

**Comment by redsolver** [comment]
Skynet can be used to backup user data, but you would need to manage encryption yourself because by default all files are public. 

I noticed two small issues with the yaml files:
- In `skydroid-dev.yaml`, `name` should ideally be a valid domain name you own, so that it can later be resolved via DNS (for example `tsacdop.stonegate.me`)
- In `skydroid-app.yaml`, `currentVersionName` and `currentVersionCode` should be empty, they are set by the `skydroid publish` script automatically based on the current values in `pubspec.yaml`

I see that the GitHub actions flow already uses Flutter, so you can simply install the SkyDroid CLI by running `flutter pub global activate skydroid_cli` in it. Then run `skydroid publish` after the APK build is done and it should work just fine.

**Comment by redsolver** [comment]
I should also note that you just need to set a `TXT` DNS record for the domain name, so other things on that domain like websites are not affected in any way.

**Comment by stonega** [comment]
@redsolver So If my domain have a CNAME record already, I can not set a TXT for it? I hace set the TXT record on t.stonegate.me, and it is searchable in skydroid.

**Comment by redsolver** [comment]
@stonega To be honest I did not consider `CNAME` records while initially designing the system, but I just implemented a solution: Starting with SkyDroid version `0.5.0` it will be possible to use the `_skydroid` subdomain for SkyDroid metadata.

So you can then set a `TXT` record for `_skydroid.tsacdop.stonegate.me` instead.

**Comment by redsolver** [comment]
SkyDroid `0.5.0` is now available, but in the meantime the IzzyOnDroid repo was bridged to SkyDroid which already contains your app: https://to.skydroid.app/com.stonegate.tsacdop.izzyondroid (see https://apt.izzysoft.de/fdroid/index/apk/com.stonegate.tsacdop)

**Comment by stonega** [comment]
I have also published the app to official Fdroid repo, so maybe I can just remove the related  yml files?

**Comment by stonega** [comment]
@redsolver  Thanks, I will close this then.
