### ISSUE TITLE
How to add episodes to custom playlist

### ISSUE THREAD

**Issue by maparaschivei** [stonega/tsacdop#46]
Hello, I have not been able to figure out how to add an episode to a "custom" playlist. Am I missing something obvious?

I have created two playlists. 'Example 1' and 'Example 2':

![Screenshot_20210514-102928](https://user-images.githubusercontent.com/5330898/118366152-82799180-b56d-11eb-8772-2c713f8e4e97.png)

How do I add episodes to these playlists? So far the only "add to playlist" mechanism I've been able to find simply adds episodes to the default 'queue' playlist.

Regards,

**Comment by stonega** [comment]
![Screenshot_20210520-094303.png](https://user-images.githubusercontent.com/2262007/118906222-ee823e00-b94f-11eb-9d1f-2a3da28d55d4.png)

You can add episodes to playlist in multi select mode, tap the button in the image.
I need to make this more easy to use I think.
Thanks for the support!

**Comment by maparaschivei** [comment]
That worked, thank you!
