### ISSUE TITLE
Long press to mark as listened

### ISSUE THREAD

**Issue by JarlavGrenland** [stonega/tsacdop#5]
When we long press an episode on the home screen it would be nice to have the option to mark it as listen to, instead of clickin gon the episode and then market it as listened to.

Also i couldn't find a way to unmark episodes back to unlistend as sometimes i do miss click.

**Comment by stonega** [comment]
1. You can change popup menu in settings=>Layout=>Episodes popup menu.
2. You can't unmark, this feature is not supported yet, I will try to solve it in future.
Thanks your feedback!
