### ISSUE TITLE
[Feature] Skip silence

### ISSUE THREAD

**Issue by Atrate** [stonega/tsacdop#8]
It would be nice if Tsacdop had a feature to skip silent parts in podcasts —silence between words and sentences often makes up a very large part of the podcast, skipping it would make listening quicker.

Example app that has this feature: https://github.com/PaulWoitaschek/Voice

**Comment by stonega** [comment]
This feature is already on my todo list, I will keep this open until it is finished.

**Comment by stonega** [comment]
This feature has been added in v0.4.9, please have a try, and tell me if it worked for you!
Thanks!

**Comment by Atrate** [comment]
Works wonderfully, thanks!
